addSbtPlugin("com.typesafe.sbt"  % "sbt-twirl"    % "1.5.0")
addSbtPlugin("com.typesafe.play" % "sbt-plugin"   % "2.8.2")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.4.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "3.9.4")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "1.1.1")
